
zef install Digest::SHA1::Native --/test
zef install Cro::HTTP::Router --/test
zef install URI::Encode --/test
zef install Image::Markup::Utilities --/test
zef install DateTime::Grammar --/test
zef install Lingua::NumericWordForms --/test
zef install WWW::OpenAI --/test
zef install WWW::PaLM --/test
zef install WWW::Gemini --/test
zef install WWW::MistralAI --/test
zef install WWW::LLaMA --/test
zef install WWW::WolframAlpha --/test
zef install WWW::MermaidInk --/test
zef install Lingua::Translation::DeepL --/test
zef install Text::SubParsers --/test
zef install LLM::Functions --/test
zef install LLM::Prompts --/test
zef install Data::TypeSystem --/test
zef install Data::Reshapers --/test
zef install Data::Summarizers --/test
zef install Data::Generators --/test
zef install Data::ExampleDatasets --/test
zef install Data::Translators --/test
zef install Data::Importers --/test
zef install Data::Geographics --/test
zef install Data::Cryptocurrencies --/test
zef install ML::FindTextualAnswer --/test
zef install ML::NLPTemplateEngine --/test
zef install ML::AssociationRuleLearning --/test
zef install ML::ROCFunctions --/test
zef install ML::TriesWithFrequencies --/test
zef install Math::DistanceFunctions --/test
zef install Math::DistanceFunctions::Edit --/test
zef install Math::SpecialFunctions --/test
zef install Statistics::Distributions --/test
zef install Statistics::OutlierIdentifiers --/test
zef install ML::Clusternig --/test
zef install Algorithm::KDimensionalTree --/test
zef install Math::Nearest --/test
zef install DSL::Entity::AddressBook --/test
zef install DSL::Entity::Geographics --/test
zef install DSL::Entity::MachineLearning --/test
zef install DSL::Entity::Metadata --/test
zef install DSL::Entity::WeatherData --/test
zef install DSL::FiniteStateMachines --/test
zef install DSL::English::ClassificationWorkflows --/test
zef install DSL::English::DataQueryWorkflows --/test
zef install DSL::English::LatentSemanticAnalysisWorkflows --/test
zef install DSL::English::QuantileRegressionWorkflows --/test
zef install DSL::English::RecommenderWorkflows  --/test
zef install JavaScript::D3 --/test
zef install Graph --/test
zef install Text::Plot --/test
zef install Text::CodeProcessing --/test
zef install Jupyter::Chatbook --/test

## Additional
zef install Chemistry::Stoichiometry --/test
zef install EBNF::Grammar --/test
zef install FunctionalParsers --/test
zef install Grammar::TokenProcessing --/test
zef install Lingua::Stem::Portuquese --/test
zef install Lingua::Stem::Russian --/test
zef install Proc::ZMQed --/test
zef install Markdown::Grammar --/test
zef install UML::Translators --/test
zef install Text::Calendar --/test
zef install Mathematica::Serializer --/test

zef install Geo::Basic --/test
